name: CD - Deploy to EC2

on:
   workflow_run:
     workflows: ["CI - Build & Test"]
      types: 
        - completed

env:
  IMAGE_NAME: taskboard-fastapi
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  

      - name: Upload static files to S3
        run: |
          echo "Subiendo archivos estÃ¡ticos a S3..."
          aws s3 sync ./app/static s3://${{ secrets.S3_BUCKET }}/static/ --delete
          echo "âœ… Archivos sincronizados correctamente."

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          echo "ðŸš€ Conectando a EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST}} << 'EOF'
            set -e
            echo "Descargando la nueva imagen desde GHCR..."
            docker pull ghcr.io/${{ github.repository_owner }}/taskboard-fastapi:latest

            echo "Eliminando contenedor anterior..."
            docker rm -f taskboard-fastapi || true

            echo "Iniciando nuevo contenedor..."
            docker run -d --name taskboard-fastapi \
              -p 80:80 \
              ghcr.io/${{ github.repository_owner }}/taskboard-fastapi:latest

            echo "âœ… Despliegue completado con Ã©xito."
          EOF
