name: CI - Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: taskboard-fastapi
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd app
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: Run basic tests
        run: |
          pytest -v || echo "âš ï¸ Tests faltantes: CI solo valida construcciÃ³n por ahora."

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Normalize registry and image name
        run: |
          REGISTRY_LC=$(echo "${{ env.REGISTRY }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME_LC=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "REGISTRY=$REGISTRY_LC" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME_LC" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: |
          TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "$TAG" > tag.txt
          echo "ðŸ§© Tag generado: $TAG"

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${TAG} .

      - name: Push Docker image to GHCR
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${TAG}

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: tag.txt
